### ISSUE TITLE
dependency issues and error when attempting the Prompter (windows)

### ISSUE THREAD

**Issue by BrBr-Prime** [InfoSecInnovations/concierge#16] opened 2024-03-13 07:08 UTC
ModuleNotFoundError: No module named 'configobj' (fixed with a "pip install")

after the above installed, refreshed the screen and the progress bar started crunching information, then this:  
  
`mistral model not found. Please wait while it loads.`  
`Loading Language Model: 3.83GB [01:50, 37.2MB/s]                                                                       2024-03-13 00:04:17.233 Uncaught app exception`  
`Traceback (most recent call last):`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script`  
 `exec(code, module.__dict__)`  
 `File "C:\Users\bryan\concierge\pages\Prompter.py", line 43, in <module>`  
 `LoadLLMModel()`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 210, in wrapper`  
 `return cached_func(*args, **kwargs)`  
 `^^^^^^^^^^^^^^^^^^^^^^^^^^^^`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 239, in __call__`  
 `return self._get_or_create_cached_value(args, kwargs)`  
 `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 266, in _get_or_create_cached_value`  
 `return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)`  
 `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 322, in _handle_cache_miss`  
 `computed_value = self._info.func(*func_args, **func_kwargs)`  
 `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`  
 `File "C:\Users\bryan\concierge\pages\Prompter.py", line 38, in LoadLLMModel`  
 `pbar.refresh()`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\std.py", line 1347, in refresh`  
 `self.display()`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\stqdm\stqdm.py", line 97, in display`  
 `self.st_display(**self.format_dict)`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\stqdm\stqdm.py", line 89, in st_display`  
 `self.st_progress_bar.progress(n / total)`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\elements\progress.py", line 153, in progress`  
 `progress_proto.value = _get_value(value)`  
 `^^^^^^^^^^^^^^^^^`  
 `File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\elements\progress.py", line 74, in _get_value`  
 `raise StreamlitAPIException(`  
`streamlit.errors.StreamlitAPIException: Progress Value has invalid value [0.0, 1.0]: 361910.289539`

sorry for all the problems, if they are "layer 8" please respond accordingly and close.

**Comment by sebovzeoueb** [comment] 2024-03-13 11:13
Hello Bryan,

Please add to existing issues in the future instead of creating a new one when adding more information about very similar problems!

It sounds lot to me like you may have skipped the step of entering into the venv to launch Concierge.

From our documentation:

---

If you are not in the python virtual environment, please enter it by the correct method:
Linux: `source ./bin/activate`
Windows PowerShell: `.\Scripts\Activate.ps1`

To start the web UI, run the following command:
`streamlit run Concierge.py`

---

If you used `install.py` or followed the manual install instructions, Concierge will be installed inside a Python virtual environment. This avoids globally installing all the dependencies on your whole operating system, which is what you will have done by using `pip install` outside of it.

So you must run the activate script and then launch Concierge.

Please let me know if you did in fact do this and the issue is still there!

**Comment by sebovzeoueb** [comment] 2024-03-14 12:21
We've added `launch.py` in the release 0.1.1. Using `install.py` followed by `launch.py` should avoid dependency issues.

**Closed by sebovzeoueb** 2024-03-14 12:21 UTC

**Comment by BrBr-Prime** [comment] 2024-03-14 15:29
I can confirm the venv worked on a fresh machine. I created a 30ish minute video of several install attempts using CPU and GPU instances. Forgive the roughness of the video... [https://youtu.be/smgo9-eN4Ek](https://youtu.be/smgo9-eN4Ek)  
  
thanks for making concierge
