### ISSUE TITLE
documentation and dependencies

### ISSUE THREAD

**Issue by BrBr-Prime** [InfoSecInnovations/concierge#14] opened 2024-03-13 06:36 UTC
Your current instructions mention nothing about Streamlit, what it is, and how to install it.

**pip install Streamlit**

also initial start failed because 'pymilvus' was missing. quick "**pip install pymilvus**"  
  
error message:

```

 You can now view your Streamlit app in your browser.
 Local URL: http://localhost:8501
 Network URL: http://192.168.1.17:8501
2024-03-12 23:17:17.653 Uncaught app exception
Traceback (most recent call last):
 File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
   exec(code, module.__dict__)
 File "C:\Users\bryan\concierge\Concierge.py", line 3, in <module>
   from concierge_streamlit_lib.status import sidebar_status
 File "C:\Users\bryan\concierge\concierge_streamlit_lib\status.py", line 3, in <module>
   from concierge_backend_lib.collections import get_collections
 File "C:\Users\bryan\concierge\concierge_backend_lib\collections.py", line 1, in <module>
   from pymilvus import connections, utility, Collection, FieldSchema, DataType, CollectionSchema
ModuleNotFoundError: No module named 'pymilvus'"
```

Perhaps you can check for the existence of those prior to final install and grab those just in case? 

Also, had to do a fresh re-install because the ollama container would not bind to 11434... quick google search found that **rebooting your machine freed up the port,** like the install started another ollama and didn't give up the port.

Did the install on Windows 11 latest patches (March 2024)

Sorry if I posted too much in one 'bug', I don't submit bugs often.

**Comment by sebovzeoueb** [comment] 2024-03-13 11:03
Duplicate of #16

**Closed by sebovzeoueb** 2024-03-13 11:03 UTC
