### ISSUE TITLE
dependency issues when attempting "Loader" (windows)

### ISSUE THREAD

**Issue by BrBr-Prime** [InfoSecInnovations/concierge#15] opened 2024-03-13 07:01 UTC
Created a new collection, then clicked on "Loader". this is the error in the terminal and webpage. several dependency checks 

ModuleNotFoundError: No module named 'langchain\_community'

ModuleNotFoundError: No module named 'stqdm'  
  
ModuleNotFoundError: No module named 'pympler'

ModuleNotFoundError: No module named 'langchain'

ModuleNotFoundError: No module named 'sentence\_transformers'

all easily solved by **"pip install"** commands, you don't even need to reboot the system. I did install the latest Python using winget, then using the windows store, so not sure if either/or caused the issue. Might want to suggest a specific install site for windows types.

**Comment by sebovzeoueb** [comment] 2024-03-13 11:03
Duplicate of #16

**Closed by sebovzeoueb** 2024-03-13 11:03 UTC
